# Generated by Django 5.2.4 on 2025-07-28 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='travel_time',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Estimated travel time for this route'),
        ),
    ]
