# Generated by Django 5.2.4 on 2025-07-29 00:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        ('routes', '0002_route_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='days_of_week',
            field=models.CharField(default='1234567', help_text='Days of week (1=Monday, 7=Sunday)', max_length=7),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='effective_from',
            field=models.DateField(default=datetime.date(2025, 7, 29), help_text='Date from which this schedule is effective'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busschedule',
            name='effective_until',
            field=models.DateField(blank=True, help_text='Date until which this schedule is effective', null=True),
        ),
        migrations.CreateModel(
            name='DynamicBusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('next_available_date', models.DateField(help_text='Date when bus becomes available for next assignment')),
                ('next_available_time', models.TimeField(help_text='Time when bus becomes available for next assignment')),
                ('is_active', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus')),
                ('current_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_assignments', to='routes.route')),
            ],
            options={
                'unique_together': {('bus', 'departure_date', 'departure_time')},
            },
        ),
    ]
