# Generated by Django 5.2.4 on 2025-07-30 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        ('routes', '0003_busschedule_days_of_week_busschedule_effective_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicbusassignment',
            options={'ordering': ['-departure_date', '-departure_time']},
        ),
        migrations.AddField(
            model_name='busschedule',
            name='buffer_hours',
            field=models.PositiveIntegerField(default=2, help_text='Buffer hours between arrival and next departure'),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='return_schedule_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic return journey scheduling'),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='schedule_type',
            field=models.CharField(choices=[('morning', 'Morning (6:00-12:00)'), ('afternoon', 'Afternoon (12:00-18:00)'), ('evening', 'Evening (18:00-24:00)'), ('night', 'Night (00:00-6:00)')], default='morning', help_text='Time period classification for intelligent scheduling', max_length=20),
        ),
        migrations.AddField(
            model_name='dynamicbusassignment',
            name='assignment_type',
            field=models.CharField(choices=[('primary', 'Primary Journey'), ('return', 'Return Journey'), ('alternate', 'Alternate Day Assignment')], default='primary', max_length=20),
        ),
        migrations.AddField(
            model_name='dynamicbusassignment',
            name='return_departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicbusassignment',
            name='return_departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dynamicbusassignment',
            name='return_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_assignments', to='routes.route'),
        ),
        migrations.CreateModel(
            name='WeeklyBusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Monday of the week for this assignment')),
                ('week_end_date', models.DateField(help_text='Sunday of the week for this assignment')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.bus')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.route')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.busschedule')),
            ],
            options={
                'ordering': ['-week_start_date'],
                'unique_together': {('bus', 'route', 'week_start_date', 'schedule')},
            },
        ),
        migrations.AddField(
            model_name='dynamicbusassignment',
            name='weekly_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='routes.weeklybusassignment'),
        ),
    ]
