# Generated by Django 5.2.4 on 2025-07-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        ('routes', '0004_alter_dynamicbusassignment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicbusassignment',
            name='weekly_assignment',
        ),
        migrations.AlterModelOptions(
            name='busschedule',
            options={'ordering': ['departure_time']},
        ),
        migrations.AlterUniqueTogether(
            name='busschedule',
            unique_together={('bus', 'route', 'departure_time')},
        ),
        migrations.DeleteModel(
            name='WeeklyBusAssignment',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='buffer_hours',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='effective_from',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='effective_until',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='journey_duration',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='return_schedule_enabled',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='schedule_type',
        ),
    ]
