# Generated by Django 5.2.4 on 2025-07-30 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_remove_dynamicbusassignment_weekly_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='buffer_hours',
            field=models.PositiveIntegerField(default=2, help_text='Buffer time in hours between trips'),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='days_of_week',
            field=models.CharField(default='1234567', help_text='Days of week (1=Monday, 7=Sunday)', max_length=7),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='effective_from',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date from which this schedule is effective'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busschedule',
            name='effective_until',
            field=models.DateField(blank=True, help_text='Date until which this schedule is effective', null=True),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='return_schedule_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic return journey scheduling'),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='schedule_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], default='morning', max_length=20),
        ),
    ]
