# Generated by Django 5.2.4 on 2025-08-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuspreference',
            name='max_budget',
            field=models.PositiveIntegerField(default=2000, help_text='Maximum budget per ticket in NPR'),
        ),
        migrations.AddField(
            model_name='userbuspreference',
            name='preferred_bus_types',
            field=models.ManyToManyField(blank=True, related_name='user_preferences', to='buses.bustype'),
        ),
        migrations.AddField(
            model_name='userbuspreference',
            name='preferred_seat_position',
            field=models.CharField(blank=True, choices=[('window', 'Window Seat'), ('aisle', 'Aisle Seat'), ('front', 'Front Seats'), ('back', 'Back Seats')], max_length=20),
        ),
        migrations.AddField(
            model_name='userbuspreference',
            name='preferred_times',
            field=models.CharField(blank=True, help_text='Comma-separated preferred travel times', max_length=200),
        ),
    ]
