# Generated by Django 5.2.4 on 2025-08-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_userbuspreference_max_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbuspreference',
            name='bus_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.bustype'),
        ),
    ]
