# Generated by Django 5.2.4 on 2025-08-14 15:43

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_userbuspreference_bus_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='busamenity',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_busamenity_name_ci'),
        ),
    ]
