# Generated by Django 5.2.4 on 2025-07-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0006_busschedule_buffer_hours_busschedule_days_of_week_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title for the destination', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the destination')),
                ('image', models.ImageField(help_text='Upload an attractive image for this destination', upload_to='destinations/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which to display (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to show this destination on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.location')),
            ],
            options={
                'verbose_name': 'Popular Destination',
                'verbose_name_plural': 'Popular Destinations',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
