# Generated by Django 5.2.4 on 2025-07-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_window',
            field=models.BooleanField(default=False),
        ),
    ]
