# Generated by Django 5.2.4 on 2025-07-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seat_is_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.CharField(default='Unnamed Passenger', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
