# Generated by Django 5.2.4 on 2025-07-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('ime_pay', 'IME Pay'), ('fonepay', 'FonePay'), ('connectips', 'ConnectIPS'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash on Counter')], max_length=50, null=True),
        ),
    ]
