# Generated by Django 5.2.4 on 2025-08-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('esewa', 'eSewa')], max_length=50, null=True),
        ),
    ]
